packages:
  - name: flipbook
    functions:
      - name: process-video
        image: registry.digitalocean.com/mappbook-registry/flipbook-processor:latest
        web: true
        environment:
          SUPABASE_URL: ${SUPABASE_URL}
          SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
          APP_URL: ${APP_URL}
        limits:
          timeout: 540000
          memory: 4096